gazebo_motor_bridge_node:
  ros__parameters:
    joint_names:
      - L_hip_roll_joint
      - L_hip_yaw_joint
      - L_hip_pitch_joint
      - L_knee_joint
      - L_foot_pitch_joint
      - L_foot_roll_joint
      - R_hip_roll_joint
      - R_hip_yaw_joint
      - R_hip_pitch_joint
      - R_knee_joint
      - R_foot_pitch_joint
      - R_foot_roll_joint
    feedback_temperature: 35.0
