gazebo_motor_bridge_node:
  ros__parameters:
    joint_names:
      - L_hip_roll_joint
      - L_hip_yaw_joint
      - L_hip_pitch_joint
      - L_knee_joint
      - L_foot_pitch_joint
      - L_foot_roll_joint
      - R_hip_roll_joint
      - R_hip_yaw_joint
      - R_hip_pitch_joint
      - R_knee_joint
      - R_foot_pitch_joint
      - R_foot_roll_joint
    kp: [40.0, 40.0, 60.0, 60.0, 10.0, 10.0, 40.0, 40.0, 60.0, 60.0, 10.0, 10.0]
    kd: [3.0, 3.0, 4.0, 4.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0, 2.0, 2.0]
    feedback_temperature: 35.0
