controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    joints:
      - joint_01
      - joint_02
      - joint_03
      - joint_04
      - joint_05
      - joint_06
      - joint_07
      - joint_08
      - joint_09
      - joint_10
      - joint_11
      - joint_12
      - joint_13
      - joint_14
      - joint_15
      - joint_16
      - joint_17
      - joint_18
      - joint_19
      - joint_20
      - joint_21
      - joint_22
      - joint_23
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
