controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: forward_command_controller/ForwardCommandController

joint_group_effort_controller:
  ros__parameters:
    joints:
      - L_hip_roll_joint
      - L_hip_yaw_joint
      - L_hip_pitch_joint
      - L_knee_joint
      - L_foot_pitch_joint
      - L_foot_roll_joint
      - R_hip_roll_joint
      - R_hip_yaw_joint
      - R_hip_pitch_joint
      - R_knee_joint
      - R_foot_pitch_joint
      - R_foot_roll_joint
    interface_name: effort
