controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    joints:
      - L_hip_roll_joint
      - L_hip_yaw_joint
      - L_hip_pitch_joint
      - L_knee_joint
      - L_foot_pitch_joint
      - L_foot_roll_joint
      - R_hip_roll_joint
      - R_hip_yaw_joint
      - R_hip_pitch_joint
      - R_knee_joint
      - R_foot_pitch_joint
      - R_foot_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
